Initial commit for aws s3 remove full access to authenticated users
vmware-samples/secure-state-remediation-jobs pull request #118
Opened 2021-09-21 06:36 UTC by sreedevikr

The commit includes the code changes for removing the full access privileges for aws authenticated users. Please provide us more information about the rule id , we have not updated the rule id for this remediation.

2021-09-21 16:14 UTC, Manmohan-Tyagi submitted a review, later dismissed

2021-09-22 14:51 UTC, kshrutik requested changes

2021-09-22 14:51 UTC, kshrutik commented on remediation_worker/jobs/aws_s3_remove_fullaccess_authenticatedusers/README.md
> +5c8c26617a550e1fb6560c69
Rule Id for s3 full access for authenticated users is this - 5c8c26567a550e1fb6560c5d

2021-09-22 14:51 UTC, kshrutik commented on remediation_worker/jobs/aws_s3_remove_fullaccess_authenticatedusers/README.md
> +The S3 bucket policy allows unrestricted access
"S3 bucket should not give full access to all authenticated users" - this is the rule name.

2021-09-22 14:51 UTC, kshrutik commented on remediation_worker/jobs/aws_s3_remove_fullaccess_authenticatedusers/README.md
> +The provided AWS credential must have access to `s3:PutBucketPublicAccessBlock`.
The provided AWS credential must have access to `s3:GetBucketAcl` and `s3:PutBucketAcl`

2021-09-22 15:55 UTC, kshrutik commented
Please add unit test

2021-09-23 11:03 UTC, kshrutik commented
Also, can you please update the main readme file and the tox file? Run the tox file and verify if the unit tests are passing.
Refer this [PR](https://github.com/vmware-samples/secure-state-remediation-jobs/pull/97)

2021-09-23 15:09 UTC, sreedevikr commented on remediation_worker/jobs/aws_s3_remove_fullaccess_authenticatedusers/aws_s3_remove_fullaccess_authenticatedusers.py
> +
@kshrutik Thanks for the review comments  .  I have included the fix for the review comments. Could you please review .

2021-09-24 05:45 UTC, sreedevikr commented
@kshrutik Thanks for the review comments.Updated the main readme and the tox file

2021-09-28 08:18 UTC, kshrutik approved these changes

2021-10-01 11:40 UTC, merged